# Generated by Django 2.2.6 on 2019-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20191129_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='About',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='Facebook',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='Instagram',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='Website',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='Youtube',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='blog',
            name='flaOrganizeTrips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='flaTravelWithAnimals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='flaTravelWithChildren',
            field=models.BooleanField(default=False),
        ),
    ]
